name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Debug Directory Structure
      run: |
        pwd
        ls -la
        echo "Frontend directory:"
        ls -la frontend/
        echo "Public directory:"
        ls -la frontend/public/
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build
      run: |
        cd frontend
        npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        
    - name: Verify Build Output
      run: |
        echo "Current directory: $(pwd)"
        echo "Build directory contents:"
        ls -la frontend/build/
        echo "Build directory size:"
        du -sh frontend/build/
        
    - name: Change to Root Directory
      run: |
        pwd
        ls -la
        echo "Current working directory: $(pwd)"
        
    - name: Verify Build Directory Exists
      run: |
        echo "Checking if frontend/build exists:"
        if [ -d "frontend/build" ]; then
          echo "✅ frontend/build directory exists"
          echo "Contents:"
          ls -la frontend/build/
          echo "Size:"
          du -sh frontend/build/
        else
          echo "❌ frontend/build directory NOT found!"
          echo "Available directories:"
          ls -la
          echo "Frontend contents:"
          ls -la frontend/
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build